remote_theme: pmarsceill/just-the-docs
title: Research Data Management
description: Tutorials and exercises for Research Data management workshops
# Aux links for the upper right navigation
baseurl: "/RDM_Workshop" # the subpath of your site, e.g. /blog
url: "https://selgebali.github.io" # the base hostname & protocol for your site, e.g. http://example.com
aux_links:
  "View on GitHub":
    - "//github.com/selgebali/RDM_Workshop"
# Footer content appears at the bottom of every page's main content
footer_content: "This project is licensed under the terms of the <a href=\"https://choosealicense.com/licenses/cc-by-4.0/\"> CC-BY-4.0 license.</a>"
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
# Footer "Edit this page on GitHub" link text
#gh_edit_link: true # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub"
#gh_edit_repository: "https://github.com/selgebali/RDM_Workshop" # the github URL for your repo
#gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
color_scheme: dark
#logo: /img/logo2.png
